---
galaxy_info:
  role_name: routeros_poe
  author: David Igou
  description: Control PoE power state on MikroTik RouterOS switch ports connected to Armbian boards
  license: GPL-3.0-or-later
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - linux
    - networking
    - infrastructure
    - routeros
    - mikrotik
    - poe

dependencies: []
