# inventory/group_vars/rock_5a.yml
---
armbian_board_config_model:
  armbian_board_name: rock-5a
  dtb: rockchip/rk3588s-rock-5a.dtb

armbian_build_model:
  branch: edge
  userpatches:
    - dest: config/boards/rock-5a.conf
      content: |
        function post_family_config_branch_edge__999_rock5a_use_mainline_uboot() {
            [[ "${BOARD}" != "rock-5a" ]] && return 0
            [[ "${BRANCH}" != "edge" ]] && return 0
            display_alert "${BOARD}" "swapping Radxa fork for mainline u-boot v2026.04" "info"
            declare -g BOOTBRANCH="tag:v2026.04"
            declare -g BOOTPATCHDIR="v2026.04"
        }
